name: Playwright Bulk Video Automation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tsx logic/automation/input.txt'
  workflow_dispatch:

jobs:
  generate-videos:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tsx logic
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Chromium
      run: npx playwright install --with-deps chromium

    - name: Run TSX to Video Automation
      run: xvfb-run --server-args="-screen 0 1920x1080x24 -ac" --auto-servernum -- node automation/recorder.js

    - name: Upload Generated Videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: generated-videos
        path: tsx logic/downloads/
        retention-days: 1
        if-no-files-found: warn
